language: php
php:
  - '5.6'
  - '7.0'

dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

before_script:
  - mysql -u root -e 'create database family_test;'
  - composer self-update
  - composer install --no-interaction

script: ./vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always